project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Die Tafelstube"
  author: "Lena-Marie Hoppe"
  date: "2024-06-14"
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - tafelstube.ipynb
    #Rename notebook to Tafelstube/room you are doing
  repo-url: https://github.com/lenskatala/tafelstube-notebook
  repo-actions: [edit]                    #[issue] zum Fragestellen
  downloads: [pdf,docx,epub]
  cover-image: images/fmd10005852a.jpg    #austauschen, hochladen nicht vergessen

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at https://quarto.org/docs/output-formats/html-themes.html
    theme: litera
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  pdf:
    documentclass: book
  docx: 
    toc: true
  epub: 
    toc: true    
